spring:
  application:
    name: post-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/postedDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update # create and drop table, good for testing, production set to none or comment it
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: user
      password: password
  kafka:
    bootstrap-servers: localhost:9092 #172.31.0.2:9092
    producer:
      #bootstrap-servers: localhost:9092  # update once pushed to container
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: DEBUG
        kafka: DEBUG
      apache:
        kafka: DEBUG

# jwt:
#   secret: RqqTGTbrokhLH59FhcdeQfQIloa7zR/ZIhaBzGPRZzAGVJgWx9faoewBE0JQcGguuC4B1PIzXPxPufaBMdBV0Q==
#   expiration: 3600000  # 1 hour in milliseconds
