spring:
  application:
    name: eureka-service
  security:
    user:
      name: admin
      password: password

server:
  port: 8761

eureka:
  instance:
      prefer-ip-address: true
      hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

#change to off
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO